title: SIGAI@UCF
email: ucfsigai@gmail.com
description: >
  We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.
baseurl: ""
url: "https://ucfsigai.github.io"

# build settings
markdown: kramdown
permalinks: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - .github/
  - .docker/
  - _meetings/__admin__/
  - _meetings/.docker/
  - _course/__admin__/
  - _course/.docker/
  - .gitignore
  - .gitmodules
  - LICENSE.md
  - vendor/

include:
  - _meetings/.docker/.jupter/custom/custom.css

collections:
  hackpack:
    output: true
    permalink: /hackpack/:path
  meetings:
    output: true
    permalink: /meetings/:path
  course:
    output: true
    permalink: /course/:path
  static:
    output: true
    permalink: /:path

defaults:
  - scope:
      type: hackpack
    values:
      layout: hackpack
  - scope:
      type: meetings
    values:
      layout: meetings
  - scope:
      type: course
    values:
      layout: course
  - scope:
      type: static
    values:
      layout: pages
