# Meta information for club stuff
meta:
  semester:     fa17
  meet_day:     Wednesday
  meet_time:    7:30pm
  mtg_room:     VAB 113
  mission:      We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.
  sign_in_url:  https://docs.google.com/forms/d/e/1FAIpQLScLRmQIo3MnEjgPY38y2_nXJMrJ8yQh48qXywEY7Jp3XuMtBA/viewform

paper_decoder:
  - A: Advanced
  - N: Novice
  - S: Short
  - L: Long

title: SIGAI@UCF
email: ucfsigai@gmail.com
description: >
  We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.
baseurl: ""
url: "https://ucfsigai.github.io"

social:
  gh:     https://github.com/ucfsigai
  yt:     https://youtube.com/channel/UCSraILnIqJ-4oqCPp-VzxWQ
  fbg:    https://facebook.com/groups/ucfsigai
  fbp:    https://facebook.com/ucfsigai
  slack:  https://acmatucf.slack.com/messages/C0PK124LS/team/U1YFXT695/

# build settings
future: true
markdown: kramdown
permalinks: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - .github/
  - Dockerfile
  - docker-compose.yml
  - .gitignore
  - .gitmodules
  - LICENSE.md

include: ["_pages"]
permalinks: /:title/

collections:
  hackpack:
    output: true
  post-indices:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title/
  - scope:
      path: ""
      type: "post-indices"
    values:
      layout: "semester-master"
      permalink:  /:title/
  - scope:
      path: ""
      type: "hackpack"
    values:
      layout: "hackpack"
      permalink: /hackpack/:path


nav:
  global:
  - title:  Now
    url:    /now
  - title:  Hackpack
    url:    /hackpack
  - title:  Archives
    url:    /archives
  - title:  About Us
    url:    /about
  - title:  FAQs
    url:    /faqs

  hackpack:
    - papers
    - novels
    - textbooks
    - moocs
    - tutorials