semester: sp18
meet:
  day:  Thursday
  time: 7:30pm
  room: HEC 103
mission: We’re on a mission to foster a hotspot for the next generation of artificial intelligence researchers and engineers at UCF.